version: '3.8' # Use a suitable version for your Docker Engine and Compose file compatibility
services:
  neo4j:
    image: neo4j:5.16.0-bullseye
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/your_password