apiVersion: v1
kind: Service
metadata:
  name: code-server-ui-svc
  namespace: code-server   
spec:
  tls:
    termination: edge
  selector:                  
    app: code-server-ui
  ports:
  - nodePort: 0
    port: 80
    protocol: TCP
